//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnLibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public int imagenID { get; set; }
        public int imagenLibro { get; set; }
        public string imagenArchivo { get; set; }
    
        public virtual Libro Libro { get; set; }
    }
}
