//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnLibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int libroID { get; set; }
        public int libroSala { get; set; }
        public int libroMateria { get; set; }
        public string libroNombre { get; set; }
        public string libroAutor { get; set; }
        public decimal libroPrecio { get; set; }
        public string libroISBN { get; set; }
        public string libroSinopsis { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
