//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnLibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int pedidoID { get; set; }
        public int librosalaID { get; set; }
        public int clienteID { get; set; }
        public string vendedorID { get; set; }
        public int estadopedidoID { get; set; }
        public int cantidadPedido { get; set; }
        public decimal subTotalPedido { get; set; }
        public decimal ivaPedido { get; set; }
        public decimal totalPedido { get; set; }
        public System.DateTime fechaInicioPedido { get; set; }
        public Nullable<System.DateTime> fechaFinPedido { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
        public virtual LibroSala LibroSala { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
