//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnLibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variables
    {
        public int variableID { get; set; }
        public string variableNombre { get; set; }
        public Nullable<decimal> variableValorNumerico { get; set; }
        public string variableValorString { get; set; }
    }
}
