//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnLibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Listar_Libros_Materia_Sala_Libreria
    {
        public int libroID { get; set; }
        public string libroNombre { get; set; }
        public string libroAutor { get; set; }
        public string libroISBN { get; set; }
        public string libroSinopsis { get; set; }
        public int materiaID { get; set; }
        public string materiaNombre { get; set; }
        public int salaID { get; set; }
        public string salaNombre { get; set; }
        public int libreriaID { get; set; }
        public string libreriaNombre { get; set; }
        public int cantidadLibroSala { get; set; }
        public decimal precioLibroSala { get; set; }
        public bool estadoLibroSala { get; set; }
    }
}
