//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnLibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Listar_Pedidos_PorLiquidar
    {
        public int clienteID { get; set; }
        public Nullable<decimal> totalSubTotal { get; set; }
        public Nullable<decimal> totalIva { get; set; }
        public Nullable<decimal> totalPedido { get; set; }
        public Nullable<int> totalCantidadPedido { get; set; }
        public Nullable<int> totalPedidos { get; set; }
    }
}
