//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnLibreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Listar_Libros_Materia
    {
        public int libroID { get; set; }
        public string libroNombre { get; set; }
        public string libroAutor { get; set; }
        public string libroISBN { get; set; }
        public string libroSinopsis { get; set; }
        public Nullable<bool> libroIVA { get; set; }
        public int materiaID { get; set; }
        public string materiaNombre { get; set; }
    }
}
